account/urls.py
from django.urls import path, include
from account.views import ProfileView, UserSignUpView, UserActivateView

app_name = 'account'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', UserActivateView.as_view(), name='activate'),

]

app/currency/api/urls.py
# from django.urls import path
# from app.currency.api.views import RateListAPIView, RateDetailsAPIView

from app.currency.api.views import RateViewSet, SourceViewSet, ContactUsViewSet

from rest_framework import routers

router = routers.SimpleRouter(trailing_slash=True)
router.register(r'rates', RateViewSet, basename='rate')
router.register(r'source', SourceViewSet, basename='source')
router.register(r'contactus', ContactUsViewSet, basename='contactus')

app_name = 'currency_api'

urlpatterns = router.urls

# urlpatterns = [
#
#     # path('rates/', RateListAPIView.as_view(), name='rate-list'),
#     # path('rates/<int:pk>/', RateDetailsAPIView.as_view(), name='rate-details'),
#
# ] + router.urls

app/currency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from app.currency.views import (
    RateListView,
    RateCreateView,
    RateUpdateView,
    RateDeleteView,
    RateDetailView,

    MessageListView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
    MessageDetailView,

    SourceListView,
    SourceCreateView,
    SourceUpdateView,
    SourceDeleteView,
    SourceDetailView,

)

# app_name = 'currency'

urlpatterns = [

                  path('rate/list/', RateListView.as_view(), name='rate-list'),  # метод ставится с ()
                  path('rate/create/', RateCreateView.as_view(), name='rate-create'),
                  path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
                  path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
                  path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),

                  path('message/list/', MessageListView.as_view(), name='message-list'),
                  path('message/create/', MessageCreateView.as_view(), name='message-create'),
                  path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='message-update'),
                  path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message-delete'),
                  path('message/details/<int:pk>/', MessageDetailView.as_view(), name='message-details'),

                  path('source/list/', SourceListView.as_view(), name='source-list'),
                  path('source/create/', SourceCreateView.as_view(), name='source-create'),
                  path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
                  path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
                  path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin

from app.currency.views import IndexView, ProfileView

from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
# from app.currency.views import HomePageView, test_view
from app.currency.views import HomePageView

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Currency API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
                  path('admin/', admin.site.urls),

                  path('auth/', include('django.contrib.auth.urls')),
                  path('auth/', include('account.urls')),

                  path('', include('app.currency.urls')),

                  path('api/currency/', include('app.currency.api.urls')),

                  path('api/account/', include('account.api.urls')),

                  path('', IndexView.as_view(), name='Index'),
                  # path('test/', test_view),

                  path('', HomePageView.as_view(), name='home'),
                  # документация
                  path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
                  path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
                  path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

                  # Сброс пароля
                  path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
                  path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _
from app.currency.choices import (
    CurrencyTypeChoices,  # Это вызов через созданный в Choices класс
    SOURCE_TYPE,
    SOURCE_URL_TYPE,
    CURRENCY_PRIVAT,
)
from django.contrib.auth.models import AbstractUser

from django.templatetags.static import static


# RATE _________________________________________________________________________
class Rate(models.Model):
    buy = models.DecimalField(_('Buy'), max_digits=6, decimal_places=2)
    sell = models.DecimalField(_('Sell'), max_digits=6, decimal_places=2)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    # type = models.CharField(_('Type'),
    #                         max_length=50,
    #                         choices=CurrencyTypeChoices.choices,
    #                         default=CurrencyTypeChoices.USD,)
    type = models.SmallIntegerField(
        _('Type'),
        choices=CurrencyTypeChoices.choices,
        default=CurrencyTypeChoices.USD,
    )
    # type = models.CharField(
    #     _('Type'),
    #     choices=CurrencyTypeChoices,
    #     default=CurrencyTypeChoices.USD,
    # )
    source = models.CharField(
        _('Source'),
        max_length=255,
        choices=SOURCE_TYPE,
        default=CURRENCY_PRIVAT
    )

    class Meta:
        verbose_name = _('Rate')
        verbose_name_plural = _('Rates')

    def __str__(self):
        return f'{self.buy} - {self.sell} - {self.source}'
        # return f'{self.buy} - {self.sell}'


# ContactUs_______________________________________________
class ContactUs(models.Model):
    name = models.CharField(
        _('Name'),
        max_length=64,
        default='admin'
    )
    email = models.EmailField(
        _('Email'),
        max_length=254,
        default='bond007@gmail.com'
    )
    subject = models.CharField(
        _('Subject'),
        max_length=254,
    )
    message = models.CharField(
        _('Message'),
        max_length=254
    )

    class Meta:
        verbose_name = _('Message')
        verbose_name_plural = _('Messages')




# Source______________________________________________________
class Source(models.Model):
    source_url = models.URLField(

        _('Source URL'),
        max_length=255,
        choices=SOURCE_URL_TYPE,
    )
    source_name = models.CharField(
        _('Source name'),
        max_length=64,
        choices=SOURCE_TYPE,
        default=CURRENCY_PRIVAT
    )

    code_name = models.CharField(
        _('Code name'),
        max_length=64,
        unique=True
    )


    created = models.DateTimeField(_('Created'), auto_now_add=True)
    logo = models.FileField(
        _('Logo'),
        default=None,
        null=True,
        blank=True,
        upload_to='logo/'
    )

    class Meta:
        verbose_name = _('Source')
        verbose_name_plural = _('Sources')

    @property
    def logo_url(self) -> str:
        if self.logo:
            return self.logo.url

        return static('Privat.png')

    def save(self, *args, **kwargs):
        if not self.pk:
            self.username = uuid.uuid4()

        return super().save(*args, **kwargs)

    # def __str__(self):
    #     return f'{self.source_url} - {self.source_name}'


# RequestResponseLog______________________________________________

class RequestResponseLog(models.Model):
    path = models.CharField(
        _('Path'),
        max_length=256,
    )
    request_method = models.CharField(
        _('Request method'),
        max_length=256,
    )

    time = models.FloatField(
        _('Time'),
    )

# USER_________________________________________________________________________________

app/currency/forms.py
from django import forms

from app.currency.models import Rate, ContactUs, Source


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'buy',
            'sell',
            'type',
            'source',
        )


class MessageForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'name',
            'email',
            'subject',
            'message',
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'source_url',
            'source_name',
            'logo',
        )

app/currency/api/views.py
# from rest_framework.generics import ListAPIView, RetrieveUpdateDestroyAPIView

from rest_framework.viewsets import ModelViewSet

from rest_framework.renderers import JSONRenderer
from rest_framework_xml.renderers import XMLRenderer
from rest_framework_yaml.renderers import YAMLRenderer

from app.currency.api.paginator import RatePagination, SourcePagination, ContactUsPagination
from app.currency.api.serializers import RateSerializer, SourceSerializer, ContactUsSerializer
from app.currency.filters import RateFilter, SourceFilter, ContactUsFilter
from app.currency.models import Rate, Source, ContactUs

from django_filters.rest_framework import DjangoFilterBackend, OrderingFilter

from rest_framework import filters, status

# для отправки email
from django.conf import settings
from django.core.mail import send_mail
from requests import Response


class RateViewSet(ModelViewSet):
    queryset = Rate.objects.all().order_by('-created')
    serializer_class = RateSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = RatePagination
    filterset_class = RateFilter
    filter_backends = (
        DjangoFilterBackend,
        # OrderingFilter,
    )


class SourceViewSet(ModelViewSet):
    queryset = Source.objects.all().order_by('-created')
    serializer_class = SourceSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = SourcePagination
    filterset_class = SourceFilter
    filter_backends = (
        DjangoFilterBackend,
    )


class ContactUsViewSet(ModelViewSet):
    queryset = ContactUs.objects.all().order_by()
    serializer_class = ContactUsSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = ContactUsPagination
    filterset_class = ContactUsFilter
    filter_backends = [filters.SearchFilter]
    search_fields = ['name', 'email']

    def perform_create(self, serializer):
        instance = serializer.save()

        self._send_email(instance)

        return super().perform_create(serializer)

    def _send_email(self, instance):
        recipient = settings.DEFAULT_FROM_EMAIL,
        subject = f"New Contact Us Submission: {instance.subject}"
        message = f"""
                Name: {instance.name}
                Email: {instance.email}
                Subject: {instance.subject}
                Message: {instance.message}
            """
        send_mail(
            subject,
            message,
            recipient,
            [recipient],
            fail_silently=False,
        )

    def form_valid(self, form):
        redirect = super().form_valid(form)
        self._send_email(self.object)
        return redirect

# class RateListAPIView(ListAPIView):
#     """
#     Получение данных по API от модели Rate
#     """
#     queryset = Rate.objects.all().order_by('-created')
#     # QuerySet - это концепция в Django, представляющая собой набор объектов модели базы данных, на котором можно
#     # выполнять различные запросы. Он предоставляет интерфейс для взаимодействия с базой данных и извлечения данных.
#     # Результаты будут отсортированы по полю created в убывающем порядке (от новых к старым)
#     serializer_class = RateSerializer
#     # Эта строка устанавливает атрибут serializer_class и указывает, что для сериализации данных
#     # (преобразования объектов Rate в формат JSON или другой формат данных) должен использоваться RateSerializer.
#     renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
#     # Определяет, какие рендереры (форматы вывода) поддерживаются для представления RateListAPIView.
#     # Рендереры отвечают за преобразование данных в определенный формат при формировании HTTP-ответа
#
#
# class RateDetailsAPIView(RetrieveUpdateDestroyAPIView):
#     """
#     Все CRUD операции кроме POST
#     """
#     queryset = Rate.objects.all().order_by('-created')
#     serializer_class = RateSerializer
#     renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)

app/currency/templates/includes/navbar.html
{#<h2>#}
{#    <a href="{% url 'rate-list' %}">Rates</a>#}
{#    <a href="{% url 'message-list' %}">Message</a>#}
{#    <a href="{% url 'source-list' %}">Source</a>#}
{##}
{#    {% if request.user.is_authenticated %}#}
{#    	Hello, {{ request.user.email }}!#}
{#        <a href="{% url 'profile' %}">Profile</a>#}
{#        <a href="{% url 'logout' %}">Logout</a>#}
{##}
{##}
{#    {% else %}#}
{#        <a href="#">Sing UP</a>#}
{#        <a href="{% url 'login' %}">Login</a>#}
{#    {% endif %}#}
{##}
{#</h2>#}
{##}


{#<p>#}
{#    <a href="/rate/list">Rates</a>#}
{#    <a href="/message/list">Message</a>#}
{#    <a href="/source/list">Source</a>#}
{##}
{#    {% if request.user.is_authenticated %}#}
{#        Hello, {{ request.user.email }}!#}
{#        <a href="{% url 'account:profile' %}">Profile</a>#}
{#        <a href="{% url 'logout' %}">Logout</a>#}
{#    {% else %}#}
{#        <a href="{% url 'account:signup' %}">Sing up</a>#}
{#        <a href="{% url 'login' %}">Login</a>#}
{#    {% endif %}#}
{#</p>#}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'Index' %}">Currency</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/rate/list">Rates <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/message/list">Message</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/source/list">Source</a>
            </li>

            {% if request.user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:profile' %}">Profile</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:signup' %}">Sing up</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>

            {% endif %}
        </ul>
    </div>
</nav>

app/currency/templates/includes/pagination.html
{#<div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if page_obj.has_previous %}#}
{#            <a href="?page=1">&laquo; first</a>#}
{#            <a href="?page={{ page_obj.previous_page_number }}">previous</a>#}
{#        {% endif %}#}
{##}
{#        <span class="current">#}
{#            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.#}
{#        </span>#}
{##}
{#        {% if page_obj.has_next %}#}
{#            <a href="?page={{ page_obj.next_page_number }}">next</a>#}
{#            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>#}
{#        {% endif %}#}
{#    </span>#}
{#</div>#}

<nav aria-label="...">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ filter_params }}" tabindex="-1">Previous</a>
            </li>
        {% endif %}

        {% for page_number in page_obj.paginator.page_range %}
            {% if page_obj.number == page_number %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ page_number }}&{{ filter_params }}">{{ page_number }}<span
                            class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="page-item">
                    <a href="?page={{ page_number }}&{{ filter_params }}" class="page-link">
                        {{ page_number }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ filter_params }}">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>


{#<nav aria-label="...">#}
{#    <ul class="pagination">#}
{#        {% if page_obj.has_previous %}#}
{#            <li class="page-item">#}
{#                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>#}
{#            </li>#}
{#        {% endif %}#}
{##}
{#        {% for page_number in page_obj.paginator.page_range %}#}
{#            {% if page_obj.number == page_number %}#}
{#                <li class="page-item active">#}
{#                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}<span#}
{#                            class="sr-only">(current)</span></a>#}
{#                </li>#}
{#            {% else %}#}
                {# Проверка, чтобы отобразить только первые три страницы, текущую страницу и последние три страницы #}
{#                {% if page_number <= 3 or page_obj.number|add:"-3" <= page_obj.number|add:"3" or page_number > page_obj.paginator.num_pages|add:"-3" %}#}
{#                    <li class="page-item">#}
{#                        <a href="?page={{ page_number }}" class="page-link">#}
{#                            {{ page_number }}#}
{#                        </a>#}
{#                    </li>#}
{#                {% elif page_number == page_obj.number|add: 4 or page_number == page_obj.number %}#}
                    {# Добавление точек между первыми тремя страницами и текущей страницей #}
{#                    <li class="page-item disabled"><span class="page-link">...</span></li>#}
{#                {% endif %}#}
{#            {% endif %}#}
{#        {% endfor %}#}
{##}
{#        {% if page_obj.has_next %}#}
{#            <li class="page-item">#}
{#                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>#}
{#            </li>#}
{#        {% endif %}#}
{#    </ul>#}
{#</nav>#}