app/currency/api/urls.py
# from django.urls import path
# from app.currency.api.views import RateListAPIView, RateDetailsAPIView

from app.currency.api.views import RateViewSet, SourceViewSet, ContactUsViewSet

from rest_framework import routers

router = routers.SimpleRouter(trailing_slash=True)
router.register(r'rates', RateViewSet, basename='rate')
router.register(r'source', SourceViewSet, basename='source')
router.register(r'contactus', ContactUsViewSet, basename='contactus')

app_name = 'currency_api'

urlpatterns = router.urls

# urlpatterns = [
#
#     # path('rates/', RateListAPIView.as_view(), name='rate-list'),
#     # path('rates/<int:pk>/', RateDetailsAPIView.as_view(), name='rate-details'),
#
# ] + router.urls

app/currency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from app.currency.views import (
    RateListView,
    RateCreateView,
    RateUpdateView,
    RateDeleteView,
    RateDetailView,

    MessageListView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
    MessageDetailView,

    SourceListView,
    SourceCreateView,
    SourceUpdateView,
    SourceDeleteView,
    SourceDetailView,

)

# app_name = 'currency'

urlpatterns = [

                  path('rate/list/', RateListView.as_view(), name='rate-list'),  # метод ставится с ()
                  path('rate/create/', RateCreateView.as_view(), name='rate-create'),
                  path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
                  path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
                  path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),

                  path('message/list/', MessageListView.as_view(), name='message-list'),
                  path('message/create/', MessageCreateView.as_view(), name='message-create'),
                  path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='message-update'),
                  path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message-delete'),
                  path('message/details/<int:pk>/', MessageDetailView.as_view(), name='message-details'),

                  path('source/list/', SourceListView.as_view(), name='source-list'),
                  path('source/create/', SourceCreateView.as_view(), name='source-create'),
                  path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
                  path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
                  path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin

from app.currency.views import IndexView, ProfileView

from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
# from app.currency.views import HomePageView, test_view
from app.currency.views import HomePageView

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Currency API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
                  path('admin/', admin.site.urls),

                  path('auth/', include('django.contrib.auth.urls')),
                  path('auth/', include('account.urls')),

                  path('', include('app.currency.urls')),

                  path('api/currency/', include('app.currency.api.urls')),

                  path('api/account/', include('account.api.urls')),

                  path('', IndexView.as_view(), name='Index'),
                  # path('test/', test_view),

                  path('', HomePageView.as_view(), name='home'),
                  # документация
                  path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
                  path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
                  path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

                  # Сброс пароля
                  path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
                  path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _
from app.currency.choices import (
    CurrencyTypeChoices,  # Это вызов через созданный в Choices класс
    SOURCE_TYPE,
    SOURCE_URL_TYPE,
    CURRENCY_PRIVAT,
)
from django.contrib.auth.models import AbstractUser

from django.templatetags.static import static


# RATE _________________________________________________________________________
class Rate(models.Model):
    buy = models.DecimalField(_('Buy'), max_digits=6, decimal_places=2)
    sell = models.DecimalField(_('Sell'), max_digits=6, decimal_places=2)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    # type = models.CharField(_('Type'),
    #                         max_length=50,
    #                         choices=CurrencyTypeChoices.choices,
    #                         default=CurrencyTypeChoices.USD,)
    type = models.SmallIntegerField(
        _('Type'),
        choices=CurrencyTypeChoices.choices,
        default=CurrencyTypeChoices.USD,
    )
    # type = models.CharField(
    #     _('Type'),
    #     choices=CurrencyTypeChoices,
    #     default=CurrencyTypeChoices.USD,
    # )
    source = models.CharField(
        _('Source'),
        max_length=255,
        choices=SOURCE_TYPE,
        default=CURRENCY_PRIVAT
    )

    class Meta:
        verbose_name = _('Rate')
        verbose_name_plural = _('Rates')

    def __str__(self):
        return f'{self.buy} - {self.sell} - {self.source}'
        # return f'{self.buy} - {self.sell}'


# ContactUs_______________________________________________
class ContactUs(models.Model):
    name = models.CharField(
        _('Name'),
        max_length=64,
        default='admin'
    )
    email = models.EmailField(
        _('Email'),
        max_length=254,
        default='bond007@gmail.com'
    )
    subject = models.CharField(
        _('Subject'),
        max_length=254,
    )
    message = models.CharField(
        _('Message'),
        max_length=254
    )

    class Meta:
        verbose_name = _('Message')
        verbose_name_plural = _('Messages')




# Source______________________________________________________
class Source(models.Model):
    source_url = models.URLField(

        _('Source URL'),
        max_length=255,
        choices=SOURCE_URL_TYPE,
    )
    source_name = models.CharField(
        _('Source name'),
        max_length=64,
        choices=SOURCE_TYPE,
        default=CURRENCY_PRIVAT
    )

    code_name = models.CharField(
        _('Code name'),
        max_length=64,
        unique=True
    )


    created = models.DateTimeField(_('Created'), auto_now_add=True)
    logo = models.FileField(
        _('Logo'),
        default=None,
        null=True,
        blank=True,
        upload_to='logo/'
    )

    class Meta:
        verbose_name = _('Source')
        verbose_name_plural = _('Sources')

    @property
    def logo_url(self) -> str:
        if self.logo:
            return self.logo.url

        return static('Privat.png')

    def save(self, *args, **kwargs):
        if not self.pk:
            self.username = uuid.uuid4()

        return super().save(*args, **kwargs)

    # def __str__(self):
    #     return f'{self.source_url} - {self.source_name}'


# RequestResponseLog______________________________________________

class RequestResponseLog(models.Model):
    path = models.CharField(
        _('Path'),
        max_length=256,
    )
    request_method = models.CharField(
        _('Request method'),
        max_length=256,
    )

    time = models.FloatField(
        _('Time'),
    )

# USER_________________________________________________________________________________

app/currency/forms.py
from django import forms

from app.currency.models import Rate, ContactUs, Source


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'buy',
            'sell',
            'type',
            'source',
        )


class MessageForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'name',
            'email',
            'subject',
            'message',
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'source_url',
            'source_name',
            'logo',
        )

app/currency/api/views.py
# from rest_framework.generics import ListAPIView, RetrieveUpdateDestroyAPIView

from rest_framework.viewsets import ModelViewSet

from rest_framework.renderers import JSONRenderer
from rest_framework_xml.renderers import XMLRenderer
from rest_framework_yaml.renderers import YAMLRenderer

from app.currency.api.paginator import RatePagination, SourcePagination, ContactUsPagination
from app.currency.api.serializers import RateSerializer, SourceSerializer, ContactUsSerializer
from app.currency.filters import RateFilter, SourceFilter, ContactUsFilter
from app.currency.models import Rate, Source, ContactUs

from django_filters.rest_framework import DjangoFilterBackend, OrderingFilter

from rest_framework import filters, status

# для отправки email
from django.conf import settings
from django.core.mail import send_mail
from requests import Response


class RateViewSet(ModelViewSet):
    queryset = Rate.objects.all().order_by('-created')
    serializer_class = RateSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = RatePagination
    filterset_class = RateFilter
    filter_backends = (
        DjangoFilterBackend,
        # OrderingFilter,
    )


class SourceViewSet(ModelViewSet):
    queryset = Source.objects.all().order_by('-created')
    serializer_class = SourceSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = SourcePagination
    filterset_class = SourceFilter
    filter_backends = (
        DjangoFilterBackend,
    )


class ContactUsViewSet(ModelViewSet):
    queryset = ContactUs.objects.all().order_by()
    serializer_class = ContactUsSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = ContactUsPagination
    filterset_class = ContactUsFilter
    filter_backends = [filters.SearchFilter]
    search_fields = ['name', 'email']

    def perform_create(self, serializer):
        instance = serializer.save()

        self._send_email(instance)

        return super().perform_create(serializer)

    def _send_email(self, instance):
        recipient = settings.DEFAULT_FROM_EMAIL,
        subject = f"New Contact Us Submission: {instance.subject}"
        message = f"""
                Name: {instance.name}
                Email: {instance.email}
                Subject: {instance.subject}
                Message: {instance.message}
            """
        send_mail(
            subject,
            message,
            recipient,
            [recipient],
            fail_silently=False,
        )

    def form_valid(self, form):
        redirect = super().form_valid(form)
        self._send_email(self.object)
        return redirect

# class RateListAPIView(ListAPIView):
#     """
#     Получение данных по API от модели Rate
#     """
#     queryset = Rate.objects.all().order_by('-created')
#     # QuerySet - это концепция в Django, представляющая собой набор объектов модели базы данных, на котором можно
#     # выполнять различные запросы. Он предоставляет интерфейс для взаимодействия с базой данных и извлечения данных.
#     # Результаты будут отсортированы по полю created в убывающем порядке (от новых к старым)
#     serializer_class = RateSerializer
#     # Эта строка устанавливает атрибут serializer_class и указывает, что для сериализации данных
#     # (преобразования объектов Rate в формат JSON или другой формат данных) должен использоваться RateSerializer.
#     renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
#     # Определяет, какие рендереры (форматы вывода) поддерживаются для представления RateListAPIView.
#     # Рендереры отвечают за преобразование данных в определенный формат при формировании HTTP-ответа
#
#
# class RateDetailsAPIView(RetrieveUpdateDestroyAPIView):
#     """
#     Все CRUD операции кроме POST
#     """
#     queryset = Rate.objects.all().order_by('-created')
#     serializer_class = RateSerializer
#     renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)

app/currency/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {#<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">#}
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Currency - {% block title %}{% endblock title %}</title>
    <title>Sample Page</title>
    <style>
        html, body {
            height: 100%;
        }

        body {
            display: flex;
            flex-direction: column;
        }

        .container {
            flex: 1;
        }
    </style>
</head>


<body>

{% include 'includes/navbar.html' %}

<div class="container">
    {% block content %}
    {% endblock content %}
</div>

<footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center">
        <span class="text-muted">
        <a href="{% url 'home' %}"><h3>Home page</h3></a>
        </span>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>


</body>


</html>

app/currency/templates/home.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
<h1>Welcome to the Home Page</h1>
<p>This is the content of your home page.</p>
{% endblock %}

{% block footer %}
<footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center">
        <span class="text-muted">{{ footer_text }}</span>
    </div>
</footer>
{% endblock %}

app/currency/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Index
{% endblock title %}

<style>
    .centered-image {
        text-align: center;
    }

    .centered-image img {
        display: inline-block;
    }
</style>


{% block content %}

    <table class="table table-striped" style="width: 100%; height: 100vh; text-align: center;">
        <tr>

            <td><img style="height: 550px; width: 800px" src="{% static 'New_yars.jpg' %}" alt="logo"></td>


    </table>


{% endblock content %}

app/currency/templates/message_list.html
{% extends 'base.html' %}

{% block title %}
    message_list
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <form method="get">
            {{ filter.form.as_p }}
            <input type="submit" />
            </form>
        </div>
    </div>

    {% if request.user.is_authenticated %}
        <a href="{% url 'message-create' %}">Message</a>
    {% endif %}

    <div class="row">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">subject</th>
                <th scope="col">message</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for contactus in object_list %}
                <tr>
                    <td style="background-color: grey"><h2>Id: {{ contactus.id }}</h2></td>
                    <td style="background-color: darkslategrey"><h2>Name: {{ contactus.name }}</h2></td>
                    <td style="background-color: lightsteelblue"><h2>Email: {{ contactus.email }}</h2></td>
                    <td style="background-color: grey"><h2>Subject: {{ contactus.subject }}</h2></td>
                    <td style="background-color: grey"><h2>Message: {{ contactus.message }}</h2></td>
                    {% if request.user.is_superuser %}
                        <td><a href="{% url 'message-update' contactus.id %}"><h2>Edit</h2></a></td>
                        <td><a href="{% url 'message-delete' contactus.id %}"><h2>Delete</h2></a></td>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <td><a href="{% url 'message-details' contactus.id %}"><h2>Details</h2></a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-12">
            {% include 'includes/pagination.html' %}
        </div>
    </div>

{% endblock content %}

app/currency/templates/message_list_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create message{% endblock title %}

{% block content %}
    Create message Form

    <form method="post">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/message_list_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block title %}Update message{%  endblock title %}

{% block content %}
    Update message Form

    <form method="post">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/rate_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Rate{%  endblock title %}

{% block content %}
    Create Rate Form

    <form method="post">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/rate_delete.html
{% extends "base.html" %}

{% block title %}Create Rate{%  endblock title %}

{% block content %}
    Are you sure want to delete rate with id {{ rate.id }}?

    <form method="post">
        {% csrf_token %}
        <button type="submit"><h1>Yes, delete</h1></button>
    </form>

{% endblock content %}

app/currency/templates/rate_list.html
{% extends 'base.html' %}

{% block title %}
    rate_list
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <form method="get">
            {{ filter.form.as_p }}
            <input type="submit" />
            </form>
        </div>
    </div>

    {% if request.user.is_authenticated %}
        <a href="{% url 'rate-create' %}">Create</a><br>
    {% endif %}



    <div class="row">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Buy</th>
                <th scope="col">Sell</th>
                <th scope="col">Type</th>
                <th scope="col">Source</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for rate in page_obj %}
                <tr>
                    <th style="background-color: slategray"><h3>Id: {{ rate.id }}</h3></th>
                    <th style="background-color: dimgrey"><h3>Buy: {{ rate.buy }}</h3></th>
                    <th style="background-color: dimgrey"><h3>Sell: {{ rate.sell }}</h3></th>
                    <th style="background-color: skyblue"><h3>Type: {{ rate.get_type_display }}</h3></th>
                    <th style="background-color: skyblue"><h3>Source: {{ rate.get_source_display }}</h3></th>
                    {% if request.user.is_superuser %}
                        <th>
                            <form action="{% url 'rate-update' rate.id %}" method="get">
                                <button type="submit">Edit</button>
                            </form>
                        </th>
                        <th>
                            <form action="{% url 'rate-delete' rate.id %}" method="get">
                                <button type="submit">Delete</button>
                            </form>
                        </th>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <th>
                            <form action="{% url 'rate-details' rate.id %}" method="get">
                                <button type="submit">Details</button>
                            </form>
                        </th>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-12">
            {% include 'includes/pagination.html' %}
        </div>
    </div>

{% endblock content %}

app/currency/templates/rate_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Update Rate{%  endblock title %}

{% block content %}
    Update Rate Form

    <form method="post">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/source_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create source{% endblock title %}

{% block content %}
    Create source

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/source_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    source_list
{% endblock title %}

{% block content %}

    <a href="{% url 'source-create' %}">Source</a>

    <table>
        <tr>
            <td style="background-color: grey"><h3>Id: {{ source.id }}</h3></td>
            <td style="background-color: darkgray"><h3>Source_url: {{ source.source_url }}</h3></td>
            <td style="background-color: dimgrey"><h3>Bank name: {{ source.source_name }}</h3></td>
            <td><img style="height: 50px; width: 50px" src="{{ source.logo_url }}" alt="logo"></td>

    </table>

{% endblock content %}

app/currency/templates/source_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    source_list
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <form method="get">
            {{ filter.form.as_p }}
            <input type="submit" />
            </form>
        </div>
    </div>

    {% if request.user.is_authenticated %}
        <a href="{% url 'source-create' %}">Source</a>
    {% endif %}


    <div class="row">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">source_url</th>
                <th scope="col">source_name</th>
                <th scope="col">logo</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for source in object_list %}
                <tr>
                    <th style="background-color: grey"><h3>Id: {{ source.id }}</h3></th>
                    <th style="background-color: darkgray"><h3>Source_url: {{ source.source_url }}</h3></th>
                    <th style="background-color: dimgrey"><h3>Bank name: {{ source.source_name }}</h3></th>
                    <th><img style="height: 50px; width: 50px" src="{{ source.logo_url }}" alt="logo"></th>
                    {% if request.user.is_superuser %}
                        <th><a href="{% url 'source-update' source.id %}"><h3>Edit</h3></a></th>
                        <th><a href="{% url 'source-delete' source.id %}"><h3>Delete</h3></a></th>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <th><a href="{% url 'source-details' source.id %}"><h3>Details</h3></a></th>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-12">
            {% include 'includes/pagination.html' %}
        </div>
    </div>

{% endblock content %}

app/currency/templates/source_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Update source{%  endblock title %}

{% block content %}
    Update source Form

    <form method="post">
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}